# Generated by Django 5.2.7 on 2025-12-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=50)),
                ('nombre_cientifico', models.CharField(max_length=70)),
                ('familia', models.CharField(max_length=50)),
                ('clima_recomendado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad_max', models.IntegerField()),
                ('clima', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('dosis_recomendada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('licencia', models.CharField(max_length=80)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('D', 'Desconocido')], max_length=1)),
                ('edad', models.IntegerField()),
                ('incorporacion', models.DateField()),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('D', 'Desconocido')], max_length=1)),
                ('fecha_nac', models.DateField()),
                ('especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.especie')),
                ('recinto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.recinto')),
            ],
        ),
        migrations.CreateModel(
            name='VacunaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('lote', models.CharField(max_length=20)),
                ('fecha_proxima_dosis', models.DateField()),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.animal')),
                ('vacuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.vacuna')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.veterinario')),
            ],
        ),
        migrations.AddField(
            model_name='vacuna',
            name='animal',
            field=models.ManyToManyField(through='mainapp.VacunaAnimal', to='mainapp.animal'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.animal')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.veterinario')),
            ],
        ),
    ]
