# Generated by Django 5.2.7 on 2025-12-10 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/animals/'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/veterinarios/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='mainapp.especie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='recinto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='mainapp.recinto'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='mainapp.animal'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='mainapp.veterinario'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='animal',
            field=models.ManyToManyField(related_name='vacunas', through='mainapp.VacunaAnimal', to='mainapp.animal'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='incorporacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('D', 'Prefiero no responder')], max_length=1),
        ),
    ]
