# Generated by Django 5.2.7 on 2025-12-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_animal_foto_veterinario_foto_alter_animal_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/veterinarios/'),
        ),
    ]
