# Generated by Django 5.2.7 on 2025-12-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_animal_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinario',
            name='edad',
        ),
        migrations.AddField(
            model_name='veterinario',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
