# Generated by Django 5.2.7 on 2025-12-17 14:54

import django.db.models.deletion
import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_veterinario_edad_veterinario_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunaanimal',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunasPuestas', to='mainapp.animal'),
        ),
        migrations.AlterField(
            model_name='vacunaanimal',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='fecha_nac',
            field=models.DateField(null=True, validators=[mainapp.models.mayor_de_edad]),
        ),
        migrations.AlterUniqueTogether(
            name='vacunaanimal',
            unique_together={('animal', 'vacuna', 'fecha_hora')},
        ),
    ]
